# Generated by Django 5.2.1 on 2025-05-13 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, unique=True)),
                ('currency', models.CharField(max_length=10)),
                ('avg_monthly_searches', models.PositiveIntegerField()),
                ('tier', models.CharField(choices=[('high', 'High'), ('mid', 'Mid'), ('niche', 'Niche')], max_length=10)),
                ('three_month_change', models.CharField(max_length=20)),
                ('yoy_change', models.CharField(max_length=20)),
                ('competition', models.CharField(max_length=20)),
                ('competition_index', models.FloatField()),
                ('bid_low', models.FloatField()),
                ('bid_high', models.FloatField()),
                ('searches_jan', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_feb', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_mar', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_apr', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_may', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_jun', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_jul', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_aug', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_sep', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_oct', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_nov', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_dec', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-avg_monthly_searches'],
            },
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=255)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pillars', to='pinterest_scheduler.campaign')),
            ],
            options={
                'ordering': ['campaign__start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headlines', to='pinterest_scheduler.pillar')),
            ],
            options={
                'ordering': ['pillar__campaign__start_date', 'pillar__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PinKeywordAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('auto_assigned', models.BooleanField(default=True)),
                ('relevance_score', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_scheduler.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='PinTemplateVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(default='', max_length=500)),
                ('cta', models.CharField(max_length=100)),
                ('background_style', models.CharField(max_length=100)),
                ('mockup_name', models.CharField(max_length=100)),
                ('badge_icon', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('link', models.URLField(blank=True, null=True)),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='pinterest_scheduler.headline')),
                ('keywords', models.ManyToManyField(blank=True, related_name='pin_variations', through='pinterest_scheduler.PinKeywordAssignment', to='pinterest_scheduler.keyword')),
            ],
            options={
                'ordering': ['headline__pillar__name', 'variation_number'],
                'unique_together': {('headline', 'variation_number')},
            },
        ),
        migrations.AddField(
            model_name='pinkeywordassignment',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_scheduler.pintemplatevariation'),
        ),
        migrations.CreateModel(
            name='ScheduledPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField()),
                ('campaign_day', models.PositiveSmallIntegerField(help_text='Campaign day from 1 to 30')),
                ('slot_number', models.PositiveSmallIntegerField(help_text='Slot position for the day')),
                ('posted', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_scheduler.board')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_pins', to='pinterest_scheduler.campaign')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_scheduler.pintemplatevariation')),
            ],
            options={
                'ordering': ['publish_date', 'campaign_day', 'slot_number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='pinkeywordassignment',
            unique_together={('pin', 'keyword')},
        ),
    ]
