# Generated by Django 5.2.1 on 2025-05-09 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headlines', to='pinterest_scheduler.pillar')),
            ],
        ),
        migrations.CreateModel(
            name='PinTemplateVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pins/')),
                ('cta', models.CharField(max_length=100)),
                ('background_style', models.CharField(max_length=100)),
                ('mockup_name', models.CharField(max_length=100)),
                ('badge_icon', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='pinterest_scheduler.headline')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField()),
                ('slot_number', models.IntegerField()),
                ('posted', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_scheduler.board')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinterest_scheduler.pintemplatevariation')),
            ],
        ),
    ]
