# Generated by Django 5.2.1 on 2025-05-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pintemplatevariation',
            name='image',
        ),
        migrations.AddField(
            model_name='pintemplatevariation',
            name='image_url',
            field=models.URLField(default='', help_text='Public image URL ending in .jpg or .png (e.g. from S3 or your CDN)', max_length=500),
        ),
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='background_style',
            field=models.CharField(help_text='Design background name or theme', max_length=100),
        ),
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='badge_icon',
            field=models.CharField(help_text='e.g. lock, chef hat, trophy', max_length=100),
        ),
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='cta',
            field=models.CharField(help_text="Call to action (e.g. 'Client-Ready Format')", max_length=100),
        ),
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='description',
            field=models.TextField(help_text='Max 500 characters. This is the Pinterest pin description.'),
        ),
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords (e.g. recipe card, editable, kitchen)', max_length=255),
        ),
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='link',
            field=models.URLField(blank=True, help_text='Target link when someone clicks the pin', null=True),
        ),
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='mockup_name',
            field=models.CharField(help_text='Which product mockup is featured', max_length=100),
        ),
    ]
