# Generated by Django 5.2.1 on 2025-05-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0002_remove_pintemplatevariation_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pintemplatevariation',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='background_style',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='badge_icon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='cta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='mockup_name',
            field=models.CharField(max_length=100),
        ),
    ]
