# Generated by Django 5.2.1 on 2025-06-03 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0002_remove_scheduledpin_posted_scheduledpin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepurposedPostStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube Shorts')], max_length=20)),
                ('repurposed_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinterest_scheduler.campaign')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repurposed_statuses', to='pinterest_scheduler.pintemplatevariation')),
            ],
            options={
                'ordering': ['-repurposed_at'],
                'unique_together': {('variation', 'platform')},
            },
        ),
    ]
