# Generated by Django 5.2.1 on 2025-05-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0003_remove_pintemplatevariation_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintemplatevariation',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
