# Generated by Django 5.2.1 on 2025-06-03 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0003_repurposedpoststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='repurposedpoststatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
