# Generated by Django 5.2.1 on 2025-06-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0004_repurposedpoststatus_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='max_variations_per_headline',
            field=models.PositiveIntegerField(default=4, help_text='Maximum variations allowed per headline for this campaign'),
        ),
    ]
