# Generated by Django 5.2.1 on 2025-05-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0004_pintemplatevariation_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintemplatevariation',
            name='variation_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pintemplatevariation',
            unique_together={('headline', 'variation_number')},
        ),
    ]
