# Generated by Django 5.2.1 on 2025-05-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0005_pintemplatevariation_variation_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpin',
            name='campaign_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Campaign day from 1 to 30'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledpin',
            name='slot_number',
            field=models.PositiveSmallIntegerField(help_text='Slot position for the day'),
        ),
    ]
