# Generated by Django 5.2.1 on 2025-06-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0005_campaign_max_variations_per_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='pillar',
            name='daily_pin_quota',
            field=models.PositiveSmallIntegerField(default=20, help_text='Total number of pins to post per day across all boards'),
        ),
        migrations.AddField(
            model_name='pillar',
            name='number_of_boards',
            field=models.PositiveSmallIntegerField(default=5, help_text='Number of boards used in this campaign'),
        ),
    ]
