# Generated by Django 5.2.1 on 2026-02-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0006_pillar_daily_pin_quota_pillar_number_of_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintemplatevariation',
            name='repurpose_hook',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pintemplatevariation',
            name='repurpose_hook_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
