# Generated by Django 5.2.1 on 2026-02-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0007_pintemplatevariation_repurpose_hook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='repurpose_hook',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
