# Generated by Django 5.2.1 on 2025-05-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0007_campaign_pillar_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintemplatevariation',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
