# Generated by Django 5.2.1 on 2025-05-12 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0008_pintemplatevariation_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['start_date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='headline',
            options={'ordering': ['pillar__campaign__start_date', 'pillar__name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='pillar',
            options={'ordering': ['campaign__start_date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='pintemplatevariation',
            options={'ordering': ['headline__pillar__name', 'variation_number']},
        ),
        migrations.AlterModelOptions(
            name='scheduledpin',
            options={'ordering': ['publish_date', 'campaign_day', 'slot_number']},
        ),
        migrations.AddField(
            model_name='scheduledpin',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_pins', to='pinterest_scheduler.campaign'),
        ),
    ]
