# Generated by Django 5.2.1 on 2025-05-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0009_alter_board_options_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, unique=True)),
                ('currency', models.CharField(max_length=10)),
                ('avg_monthly_searches', models.PositiveIntegerField()),
                ('three_month_change', models.CharField(max_length=20)),
                ('yoy_change', models.CharField(max_length=20)),
                ('competition', models.CharField(max_length=20)),
                ('competition_index', models.FloatField()),
                ('bid_low', models.FloatField()),
                ('bid_high', models.FloatField()),
                ('searches_jan', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_feb', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_mar', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_apr', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_may', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_jun', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_jul', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_aug', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_sep', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_oct', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_nov', models.PositiveIntegerField(blank=True, null=True)),
                ('searches_dec', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-avg_monthly_searches'],
            },
        ),
    ]
