# Generated by Django 5.2.1 on 2025-05-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0010_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pintemplatevariation',
            name='keywords',
        ),
        migrations.AddField(
            model_name='pintemplatevariation',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='pin_variations', to='pinterest_scheduler.keyword'),
        ),
    ]
