# Generated by Django 5.2.1 on 2025-05-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0011_remove_pintemplatevariation_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='tier',
            field=models.CharField(choices=[('high', 'High'), ('mid', 'Mid'), ('niche', 'Niche')], default='niche', max_length=10),
            preserve_default=False,
        ),
    ]
