# Generated by Django 5.2.1 on 2025-05-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0012_keyword_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
