# Generated by Django 5.2.1 on 2025-05-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest_scheduler', '0013_alter_pintemplatevariation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pintemplatevariation',
            name='image_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
